---
title: "Capstone Project Proposal"
author: "John Morse"
bibliography: capstone.bib
csl: american-political-science-association.csl
link-citations: true

papersize: letter

margin-left: 1in
margin-right: 1in
margin-top: 1in
margin-bottom: 1in
cap-location: top

format: 
  pdf:
    toc: true
    toc-depth: 2
    number-sections: true
    linestretch: 2
  html: default

execute:
  echo: false
  warning: false
  message: false
---

\clearpage

\raggedright

\setlength{\parindent}{20pt}

# Proposal

For my research project, I am studying the relationship between student literacy, as measured through standardized testing, and enrollment in post-secondary education. My intent is to use the rate at which students meet expected standards in literacy as regressor variables in predicting rates of post-secondary enrollment in 2-year and 4-year colleges. Specifically, the question I am posing through this research is: **Do SBAC ELA achievement rates in Washington state secondary schools predict post-secondary college enrollment rates?**

In a 2012 article from the Annie E. Casey Foundation, Donald Hernandez argues that both early literacy skills and poverty directly impact high school graduation rates [@Hernandez2011]. The assumption behind my research is that literacy has a cascading, or rather a building effect on students: early literacy leads to better results in later grades, which leads to better results after graduation. Reading ability and reading comprehension are the base level skills needed not just for high school graduation, but for post-secondary success as well.

According to the Education Research & Data Center (ERDC) for Washington State, the rate of enrollment in 4-year colleges has remained nearly flat over the past 10 years, while enrollment in 2-year colleges and technical schools has decreased by four percentage points. At the same time, ERDC reports rates of enrollment in college-prep English courses has dropped from 9% to 6% for 4-year college destined students and from 36% to 15% for students expecting to enter 2-year colleges or technical schools (<https://erdc.wa.gov/publications-and-reports/high-school-graduate-outcomes>).

With the decrease in enrollment, the Washington Student Achievement Council (WSAC) has set a goal that "70 percent of adults ages 25 to 44 should earn a postsecondary credential" (<https://wsac.wa.gov/strategic-action-plan>). In the 10 years ending in 2024, though, WSAC measured an 18% decrease in post-secondary enrollment (<https://wsac.wa.gov/sap-dashboard>).

At the secondary school level, Washington state uses standardized tests provided by the Smarter Balanced Assessment Consortium (SBAC) to track student achievement in English Language Arts (ELA) and Mathematics. Tests can be administered as many as eight times in a student’s secondary schooling, from grades 3 to 11. Through these test results, we can track the rate at which students are achieving expected literacy goals. These tests are given as part of normal schooling and are, therefore, representative of literacy achievement across all students, not just college-bound students. With literacy capability in secondary school strongly associated with college readiness, tracking literacy achievement through SBAC scores could be used as an indication of college enrollment.

Washington student achievement on SBAC test results, along with enrollment in college, are reported as ratios through the Washington State Open Data Portal (https://data.wa.gov) and through online dashboards provided by ERDC. Through regression analysis, I will analyze SBAC test results in respect to college enrollment rates for students at individual high schools or across school districts. A possible secondary question I am considering is whether SBAC ELA scores are more relevant to post-secondary enrollment than SBAC Math scores.

Due to student privacy, data is not available at the individual student level, and I will be working with overall rates of enrollment and rates of meeting test standards at the school and school district level. This introduces a potential risk of an ecological fallacy. During the project, I will consider leveraging socioeconomic factors including income level and ethnicity to control for potential issues.

Additionally, SBAC scores from a single year (e.g. 11^th^ grade) may not be wholly representative of student achievement and readiness. To validate the robustness of the relationship between SBAC achievement scores and post-secondary enrollment, I intend to analyze multiple perspectives of standardized test scores:

-   Most recent SBAC scores (last score reported in a school district).

-   Last two SBAC scores to smooth single test variations.

-   A simple aggregation of SBAC scores across all grades in a school district.

-   Weighted scores across all grades emphasizing later grades over earlier.

Aggregated and weighted scores across grade levels will be measured and analyzed at a school district level. As the project progresses, and if time allows within the semester, I will also examine socioeconomic factors as possible control variables, along with student participation in remedial level English courses in the first year of college.

# Annotated Bibliography

The following annotations apply to the articles identified in the **References** section of this document.

[@Cox2003]: An examination of university students entering college without the requisite literacy (reading comprehension and writing) skills to succeed. Students are identified based on test scores and grouped based on students who do not take a reading skills course, those who take a course but do not pass, and those that take a course and pass and/or get an exceptional grade (A). The authors conclude that under-prepared students are more likely to succeed in college if they have taken and passed a reading skills course. This research demonstrates the importance of literacy skills for first-year students in college and leverages data from a reading placement test to analyze student readiness.

[@Fidalgo2014]: The authors analyze reading comprehension as a hybrid task that involves multiple activities including reading, comprehending, and writing. A common example is analyzing and summarizing an article after reading it. In the analysis, the authors compare students with and without reading difficulties to understand the comprehension process and the iterative cycles used to understand and write about a topic. Of most relevance in this study is the conclusion that reading comprehension strategies do not vary as children age. Students were studied at the primary and secondary level in Spain, where the primary level includes 5th and sixth grades, while the secondary level equates to US high school. This demonstrates a consistency in literacy activities across grades and may indicate achievement scores will stay consistent as a child ages.

[@Graham2010]: A secondary analysis of survey results collected as part of a doctoral dissertation and subsequently delivered as part of a 2010 conference. The authors review and analyze the reading comprehension of first-year university students and compare against the general population in Canada as well as comparing within group by gender and by area of major study (arts, science, and business administration). Crucially, the authors determined no difference in reading comprehension from the Canadian population as a whole, indicating that literacy skills were not a factor in university enrollment. Applied broadly, universities looking to attract students may disregard literacy skills, potentially impacting student readiness and success in college.

[@Hein2013]: A literature review highlighting indicators and predictors of student success, including success in reading and writing skills. Tracks primary predictors of success at multiple levels: elementary, middle school, high school, and post-graduation. Test scores, attendance, and GPA are included as primary indicators of success, while enrollment in advanced courses and social skills also contribute to success. Intended to support the design and implementation of programs by school policymakers toward improving student performance and outcomes. The authors point out the difficulty in relating early achievement in school to post-secondary success. However, this research does note a relationship between early literacy and standardized test scores, more specifically scores on college entrance testing (ACT and SAT). Additionally, higher scores on AP and IB exams are correlated with higher rates of college enrollment.

[@Hernandez2011]: An overview of high school drop out rates linked to both literacy in third grade and poverty rates. As a link between early literacy skills and later secondary success, this article demonstrates the continuation of impact across grades as children get older. Third-grade reading assessments for the students used in this analysis are based on national scores collected through standardized testing including precursor testing to standard implemented through No Child Left Behind like SBAC.

[@Jackson2005]: An examination of the relationships of 1) component reading skills and college student reading comprehension, and 2) reading skills and student achievement in college. Reading skills are broken into word decoding, reading speed, and text comprehension. This analysis serves as a counterpoint to my work, as the author reports limited to no relationship between literacy skills and college performance. In review, though, the sample is skewed and not representative of a general college enrollment population.

[@James2024]: In this analysis, the authors analyze the educational and employment outcomes of children identified with poor reading comprehension while in elementary school. This article recognizes the impact reading comprehension issues can have on long term outcomes, even when they are identified early in the child's education (e.g. 3rd or 4th grade). The analysis is a comparison of students identified as having low reading comprehension ability with students at or above expectations. Secondary school capability is linked to post-secondary success in both education and employment. The authors also look at assessment scores (SATs) as an outcome variable.

[@Long2012]: An assessment of student test scores based on participation in advanced curriculum including Honors, Advanced Placement (AP), and other rigorous courses. The study focuses on Florida students graduating from high school in 2003. The study includes an examination of enrollment in 2-year or 4-year colleges after graduation and, as such, represents a similar analysis as proposed by my hypothesis. However, this study examines tests related to advanced and dual-credit courses such as Advanced Placement (AP) and Honors. Enrollment in ELA based advanced courses in high school demonstrated significant increases in college credits earned, grade point average, and the rate at which students earned a bachelor's degree.

[@Ozek2025]: A study of the effects of placing students in remedial reading programs in school. Such programs can be beneficial to students to bring them up to reading standards as long as the student is not "tracked" into a remedial program, i.e. restricted to remedial classes across other subjects and as they advance in school. The article is included as a counterpoint to students that demonstrate higher literary achievement. Additionally, enrollment in remedial courses can indicate lowered literacy expectations for college admissions and could alter the influence of literacy achievement in secondary schools.

[@Savolainen2008]: An analysis of students in Finland and the role of reading and spelling skills as those students pursued upper secondary education. Students, upon entering the upper secondary level of education, similar to high school in the US, have the choice of pursuing general education or vocational education. This article analyzes what role, if any, reading and spelling have on that choice and subsequent career choices. Literacy in lower grade levels is demonstrated to affect school choices in upper grade levels which, ultimately, affect post-secondary pursuits (college vs. vocational career). The relationship directly impacts college enrollment through a mid-level choice when entering the equivalent of high school.

[@Talwar2022]: Examines mulitple facets of literacy: literacy skills (including vocabulary and reading comprehension), reading strategies, and reading motivation. The research analyzes how these multiple aspects of literacy affect academic reading and student success in college. The authors introduce a new framework for assessing literacy skills. Individual students were asked to complete a custom assessment for the purposes of the research. Outcomes demonstrated the direct impact of literacy skills on college success, indicating readiness obtained prior to college directly influences that success.

[@Westall2023]: A focus on early literacy programs and their impact on student literacy by the end of third grade. Outcomes are focused on standardized test scores, both high-stakes and low-stakes testing. High-stakes testing outcomes may impact student plaement, teacher evaluations, or school ratings/funding. There is an implication that high-stakes outcomes may be the result of "teaching to the test." Low-stakes testing, on the other hand, have no direct consequences and are used pirmarily for internal monitoring of progress. The authors conclude early literacy programs can significantly impact high-stakes testing but have little impact on low-stakes testing.

# Data Sources

My primary source of data will be CSV files made available at the Washington State Open Data Portal (<http://data.wa.gov>). As part of the Office of the Superintendant of Public Instruction (OSPI), Washington state began collecting extensive data about students starting with the 2014-15 school year. Note that several data sets have gaps during the 2019-20 and 2020-21 school years due to COVID. Most data is captured at the school and school district level, with additional breakouts based on socioeconomic attributes (e.g. ethnicity and income levels). For privacy, no data is captured at the individual student level.

## Data Sources with Independent Variables

This section identifies primary data sets that include independent variables and attributes used for this project. Note that many of the data sources also include rates broken down by demographic attributes.

### School Directory

Washington School Directory: Primary source of School District and School Names. Used as a look-up table to standardize on School and School District names. `LEACode` and `SchoolCode` are used to define relationships between files where necessary. This data is available from the Office of Superintendent of Public Instruction (<https://eds.ospi.k12.wa.us/DirectoryEDS.aspx>).

-   **Variables:** LEA Code (District Code), LEA Name (District Name), School Code, School Name
-   **Observations:** 3,084 total, 342 Districts, 2,742 Schools

### Assessment

Report Card Assessment: Tracks rate of students taking standardized tests (e.g. SBAC) and the percent meeting standards based on score. This is a primary source for SBAC test information including the percent of students meeting standards. Observations are provided by school year, grade level, student demographics, test, and test subject. Missing school years 2019-20 and 2020-21. Data for the 2023-24 school year available here: [Report Card Assessment Data 2023-24 School Year \| Data.WA \| State of Washington](https://data.wa.gov/education/Report-Card-Assessment-Data-2023-24-School-Year/x73g-mrqp/about_data).

-   **Variables**: test_administration, test_subject, students_expected_to_test, percent_met_standard, percent_participation
-   **Observations**: 2.16M observations, 534,200 District level observations, 1.56M School level observations

### Graduation

Report Card Graduation: Percentage of students graduating from high school within the year. Graduation rates are considered as a secondary data source for control data. Data is captured at the State, County, District, and School level and includes separate observations by school year and by student demographics. Data for the 2023-24 school year is available here: [Report Card Graduation 2023-24 \| Data.WA \| State of Washington](https://data.wa.gov/education/Report-Card-Graduation-2023-24/76iv-8ed4/about_data).

-   **Variables**: graduation_rate
-   Observations: 830k Total, 213k Districts, 569k Schools.

### WSIF

Washington School Improvement Framework: WSIF is a means of measuring school improvement based on a range of scores including standardized testing, attendance, graduation, and dual credit class participation. A final score indicates the standing of the school for each year. This is an additional source of standardized testing results that may be used along with additional independent variables that may be necessary for control factors. Data is captured by school year, school, and student demographics. Data is missing for 2020 and 2021. Data for the 2023-24 school year is available here: [Washington School Improvement Framework (WSIF) 2024 Annual \| Data.WA \| State of Washington](https://data.wa.gov/education/Washington-School-Improvement-Framework-WSIF-2024-/8v2t-vz3j/about_data).

-   **Variables**: growth_ela_median, growth_math_median, attendance_rate, ninth_grade_on_track, dual_credit_rate, final_score
-   Observations: 149k Total

### Remedial Coursetaking

Measures the rate at which first year college students from Washington high schools take remedial courses. Remedial courses in Math and English are tracked. This supports tracking the rate at which students exit high school without the literacy or math capabilities expected in college. Data includes graduating years 2005 to 2023 and can be accessed here: [High School Graduate Outcomes - Remedial Coursetaking \| Data.WA \| State of Washington](https://data.wa.gov/education/High-School-Graduate-Outcomes-Remedial-Coursetakin/y8qh-965v/about_data).

-   **Variables**: Remedial Type, Percentage
-   **Observations:** 591k Total, 51k County, 155k Districts, 393k Schools

## Data Sources with Outcome Variables

Outcome variables are also pulled from the Washington State Open Data Portal. These track student outcomes specific to high schools within the state.

### First Year Enrollment

Captures the percent of students that enrolled in a 2-year or 4-year college within one year of graduating. Also includes the percentage not enrolled in any post-secondary education. Data includes graduating years 2005 to 2023 and can be accessed here: [High School Graduate Outcomes - First Year Enrollment by Sector \| Data.WA \| State of Washington](https://data.wa.gov/education/High-School-Graduate-Outcomes-First-Year-Enrollmen/vk6s-am8z/about_data).

-   **Variables**: Percent Enrolled, Enrollment Level
-   **Observations**: 104k Total, 40k Districts, 88k Schools

### Persistence / Retention

This data set tracks students that remain in college after the first year. This includes outcome variables that may be used if time permits. Persistence is an indication that the student stayed in college, but may have transferred schools. Retention indicates the student stayed in the same school. This is a measure of "stickiness" for college enrollment. The Persistence and Retention data includes graduating years 2005 to 2022 and is available here: [High School Graduate Outcomes - Persistence / Retention \| Data.WA \| State of Washington](https://data.wa.gov/education/High-School-Graduate-Outcomes-Persistence-Retentio/7hx3-t3pn/about_data).

-   **Variables:** Persist_Retain, Percentage
-   **Observations:** 420k Total, 172k Districts, 308k Schools

# References
